### ISSUE TITLE
UI Revisions and Map Design Changes per CBF Review

### ISSUE THREAD

**Issue by coregis** [coregis/cbf-programs-map-2023#17]
- [x] Change “RYHT” in bottom right corner to “ © CBF”
- [x] Experiment with making the lines of the districts less prominent/lighter/more transparent
- [x] CORE GIS to add lines as hard breaks between zones on side panel
- [x] Padding and lines - can we have it mimic the Figma file?
- [x] Remove “Request a site visit” links from RBL tooltips
- [x] Make CBF logo at top of side panel link to CBF website
- [x] Reduce size of credits at bottom of side panel/console
- [x] Make wrapping of legend names align with first letter of first line at CR

**Comment by coregis** [comment]
Thanks for making those changes and explaining what you did in the PR!! I just added a couple more things. Also it looks like you found the RYHT in the lower right attribution, where was that little bugger?!

**Comment by eldang** [comment]
Hahaha, @coregis while you were writing this, @nein09 and I were talking about how neither of us knew where to look for that.  So I don't think it was anything either of us did.

I'm also not sure we have _fully_ resolved that issue.  When I load the map in its current state, I see "RYHT | © Mapbox © OpenStreetMap" flash up, and then the "RYHT |" disappears by the time the point layers have finished loading.  It goes away fast enough that I'm having trouble screenshotting it, but slowly enough that some people will notice.

Weirdly, I can not find either the string "RYHT" or any reference to an [AttributionControl](https://docs.mapbox.com/mapbox-gl-js/api/markers/#attributioncontrol) or `map.customAttribution` in this project's code.  I'm wondering if there could be something associated with the Mapbox style.

One thing I did notice on that front is that we're still [loading](https://github.com/coregis/cbf-programs-map-2023/blob/045e6e89e9158e9e5e34be2fdcdbc827f85b7f99/scripts/onload.js#L255-L266) the `school_house_senate_districts_UNION` hidden layer from the CoreGIS Mapbox account instead of the new CBF one.  Could it be that there's an old attribution associated with that layer / tileset?  It would load much faster than RBL points layer, so it could be that whichever has finished loading most recently overwrites the previous attribution.  I am clutching at straws a bit though - not at all confident in this guess, just trying to think about places it could be set that I wouldn't find by searching the text of this project's files.

**Comment by eldang** [comment]
Aha!  I just realised that the "RYHT |" attribution toggles on and off with the school district boundaries layer.  So the reason it flashes on during loading is that the layer gets rendered invisibly first so we can populate the dropdown menu from its contents, before then being deactivated.  I bet the attribution is set somewhere in the tileset itself, and Mapbox just displays the superset of all custom attributions associated with currently-active layers.

**Comment by nein09** [comment]
@eldang what a find! I would never have figured that one out.

**Comment by eldang** [comment]
I don't think I would have made the connection either, if I hadn't _recently_ been tinkering with that invisible render to get the district names.

**Comment by coregis** [comment]
I FOUND THE LITTLE BUGGER! It is indeed embedded in the mbtiles:
![image](https://github.com/coregis/cbf-programs-map-2023/assets/8813214/a1ffbec8-150d-44a4-8ac4-0dd1e72a070f)
