### ISSUE TITLE
Functionality Fixes

### ISSUE THREAD

**Issue by coregis** [coregis/cbf-programs-map-2023#6]
- [x] Reconnect School District names to dropdown in console
- [x] Test zoom-to-district functionality with CBF-hosted School District vector tiles
- [x] Apply zoom-to-bounds function from Zoom to Whole State to map object onload

**Comment by eldang** [comment]
One of the issues turns out to have been that Google Sheets can't be called from a `file://` URL, so in 2d18978310005f5ee8f4d8010e5ee2d5781d1a4d I've added the usual note about running a local server.  With that, we have the point layers back:

![Screenshot 2023-11-28 at 17 19 27](https://github.com/coregis/cbf-programs-map-2023/assets/1379812/9cbd4b08-a92f-4ad1-a3ce-d745e5229f50)

**Comment by eldang** [comment]
@coregis should we also set some max bounds to prevent Duplicate Texas?

![Screenshot 2023-11-28 at 17 20 20](https://github.com/coregis/cbf-programs-map-2023/assets/1379812/acac84cd-0d09-41b0-a4a3-c15fb7b52653)

**Comment by coregis** [comment]
I don't know, maybe one of them will turn out to not be evil?!
Yes setting some max bounds is a fantastic idea.

**Comment by eldang** [comment]
Well, this wasn't too bad.  Mainly a matter of loading various things from 2 years ago back into my head....
